version: '3.1'

services:

  # nginx
  nginx:
    container_name: hades-nginx
    build: ./nginx
    restart: always
    ports:
      - 8888:80
    environment:
      - UPSTREAM_FRONTEND_IP=${UPSTREAM_FRONTEND_IP}
      - UPSTREAM_BACKEND_IP=${UPSTREAM_BACKEND_IP}

  # database
  # ref. https://hub.docker.com/_/mongo
  mongo:
    container_name: hades-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./database/db:/data/db
      - ./database/configdb:/data/configdb
    networks:
      - backend

  mongo-express:
    container_name: hades-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
    networks:
      - backend

networks:
  backend:
    driver: bridge
